version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Priority: Medium"
      - "Status: Review Needed"
      - "Subject: Dependencies"
    commit-message:
      prefix: "chore(deps)"
    assignees:
      - "azjezz"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Priority: Medium"
      - "Status: Review Needed"
      - "Subject: Dependencies"
    commit-message:
      prefix: "chore(ga)"
    assignees:
      - "azjezz"
