dist: trusty
language: php

os:
  - linux

jobs:
  include:
    - php: 7.4
    - php: nightly
      env: NIGHTLY_BUILD=true

  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache/files


install:
  - php --version
  - composer self-update
  - composer --version
  - if [[ $NIGHTLY_BUILD = 'true' ]]; then composer install --ignore-platform-reqs; else composer install; fi

script:
  - composer test:unit
  - if [[ $NIGHTLY_BUILD != 'true' ]]; then composer test:mutation; fi
  - if [[ $NIGHTLY_BUILD != 'true' ]]; then composer cs:check; fi
  - if [[ $NIGHTLY_BUILD != 'true' ]]; then composer type:check; fi
  - if [[ $NIGHTLY_BUILD != 'true' ]]; then composer security:analysis; fi

after_script:
  - if [[ $NIGHTLY_BUILD != 'true' ]]; then composer code:coverage; fi
  - if [[ $NIGHTLY_BUILD != 'true' ]]; then composer type:coverage; fi
