name: "doc check"

on: ["pull_request", "push"]

jobs:
  doc-check:
    name: "doc check"
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"

      - name: "installing PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr
          extensions: bcmath, mbstring, intl, sodium, json

      - name: "installing dependencies"
        run: "composer update --no-interaction --no-progress"

      - name: "Checking docs are up-to-date"
        run: "php doc_gen.php check"

    #  - name: "committing built doc"
    #    uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
    #    with:
          # The arguments for the `git add` command (see the paragraph below for more info)
    #      # Default: '.'
    #      add: 'docs/index.md'


